### PR TITLE
Upgrade build server to compile using C++17, mac os 10.15 and boost 1.70

### PR DESCRIPTION
**Pull request by eugene-so**
Problem 
Upgrade the following build tools:
* macOS build server 10.15 with system clang
* boost 1.70 
* Make the c++17 compiler compulsory. 
* This PR follows #960 

Root Cause 
Move toward support for MacOS Big Sur

Solution
 Port changes from bitcoin repo related to the build tools described above

Bounty PR #ZZZ
Bounty Payment Address sv1qqp6aptgvgp9t9h8sgzkqmu6cgq2e20l9x6fsl5ask7t3ygy2jagftcpq0x5z0h522ca5h06qq3hx33pke00r7gjt3j24n896gf55y68ptrmjqqqqd8lz3

Unit Testing Results 
Successful build on macOS 10.15+ and perform regression tests

### CODE REVIEW

**Comment by ianGre** [comment]
On Catalina (macOS 10.15.7) I got these errors on `make` I got these errors.

> In file included from qt/veil.cpp:28:
> In file included from ./qt/paymentserver.h:35:
> In file included from ./qt/paymentrequestplus.h:10:
> ./qt/paymentrequest.pb.h:17:2: error: This file was generated by an older version of protoc which is
> #error This file was generated by an older version of protoc which is
>  ^
> ./qt/paymentrequest.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
> #error incompatible with your Protocol Buffer headers.  Please
>  ^
> ./qt/paymentrequest.pb.h:19:2: error: regenerate this file with a newer version of protoc.
> #error regenerate this file with a newer version of protoc.
>  ^
> ./qt/paymentrequest.pb.h:27:10: fatal error: 'google/protobuf/inlined_string_field.h' file not found
> #include <google/protobuf/inlined_string_field.h>
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 7 warnings and 4 errors generated.
> make[2]: *** [qt/veil_qt-veil.o] Error 1
> make[1]: *** [all-recursive] Error 1
> make: *** [all-recursive] Error 1

I guess my protoc is too new for the paymentrequest.pb file.

**Comment by eugene-so** [comment]
> On Catalina (macOS 10.15.7) I got these errors on `make` I got these errors.
> 
> > In file included from qt/veil.cpp:28:
> > In file included from ./qt/paymentserver.h:35:
> > In file included from ./qt/paymentrequestplus.h:10:
> > ./qt/paymentrequest.pb.h:17:2: error: This file was generated by an older version of protoc which is
> > #error This file was generated by an older version of protoc which is
> > ^
> > ./qt/paymentrequest.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
> > #error incompatible with your Protocol Buffer headers.  Please
> > ^
> > ./qt/paymentrequest.pb.h:19:2: error: regenerate this file with a newer version of protoc.
> > #error regenerate this file with a newer version of protoc.
> > ^
> > ./qt/paymentrequest.pb.h:27:10: fatal error: 'google/protobuf/inlined_string_field.h' file not found
> > #include <google/protobuf/inlined_string_field.h>
> > ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 7 warnings and 4 errors generated.
> > make[2]: *** [qt/veil_qt-veil.o] Error 1
> > make[1]: *** [all-recursive] Error 1
> > make: *** [all-recursive] Error 1
> 
> I guess my protoc is too new for the paymentrequest.pb file.

Hmmm.  I think @seanPhill also saw this sometime ago.  My guess is you have two versions of protobuf installed, one from the veil configuration and one that was part of your o/s. We'll have to look into how to force the compiler to ignore the system library.

**Comment by seanPhill** [comment]
On Big Sur (macOS 11.4) I have similar, but not the same.

> In file included from qt/veil.cpp:259:
> ./qt/veil.moc:14:2: error: "This file was generated using the moc from 5.15.2. It"
> #error "This file was generated using the moc from 5.15.2. It"
>  ^
> ./qt/veil.moc:15:2: error: "cannot be used with the include files from this version of Qt."
> #error "cannot be used with the include files from this version of Qt."
>  ^
> ./qt/veil.moc:16:2: error: "(The moc has changed too much.)"
> #error "(The moc has changed too much.)"
>  ^
> ./qt/veil.moc:33:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(0, 0, 11), // "BitcoinCore"
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> ./qt/veil.moc:34:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(1, 12, 16), // "initializeResult"
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> ./qt/veil.moc:35:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(2, 29, 0), // ""
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> ./qt/veil.moc:36:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(3, 30, 7), // "success"
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> ./qt/veil.moc:37:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(4, 38, 14), // "shutdownResult"
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> ./qt/veil.moc:38:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(5, 53, 16), // "runawayException"
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> ./qt/veil.moc:39:1: error: use of undeclared identifier 'Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET'
> QT_MOC_LITERAL(6, 70, 7), // "message"
> ^
> ./qt/veil.moc:27:5: note: expanded from macro 'QT_MOC_LITERAL'
>     Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
>     ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 12 warnings and 20 errors generated.
> make[2]: *** [qt/veil_qt-veil.o] Error 1
> make[1]: *** [all-recursive] Error 1
> make: *** [all-recursive] Error 1
>

**Comment by eugene-so** [comment]
@ianGre : Can you type these two commands on your system and let me know what you get:

protoc --version

brew info protobuf

Thanks

**Comment by ianGre** [comment]
```
~ % protoc --version
libprotoc 3.17.3
```

```
~ % brew info protobuf
protobuf: stable 3.17.3 (bottled), HEAD
Protocol buffers (Google's data interchange format)
https://github.com/protocolbuffers/protobuf/
/usr/local/Cellar/protobuf/3.17.3 (210 files, 18MB) *
  Poured from bottle on 2021-07-18 at 08:07:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/protobuf.rb
License: BSD-3-Clause
==> Dependencies
Build: python@3.9 ✔
Required: six ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/protobuf
==> Analytics
install: 95,155 (30 days), 416,866 (90 days), 1,622,627 (365 days)
install-on-request: 18,214 (30 days), 83,358 (90 days), 305,244 (365 days)
build-error: 0 (30 days)
```

**Comment by eugene-so** [comment]
@ianGre : Just wondering, have you compiled this in the past or is it a clean clone?  I read on the bitcoin forums someone else ran into something similar and doing this resolved the issue right away:

Try a ‘make clean’, and re-run autogen, configure and make.

**Comment by eugene-so** [comment]
@ianGre  : I installed protobuf 3.17.3, the version you have, and was able to successfully build from after cleaning.  Would be good if you could confirm as well.

**Comment by ianGre** [comment]
Maybe! I will try again.

**Comment by seanPhill** [comment]
My Big Sur attempt failed. A bunch of "undeclared identifier" errors in /usr/local/Cellar/qt@5/5.15.2/lib/QtCore, plus "deprecated' attribute cannot be applied to types", and the first error:
```
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/QMenu:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/qmenu.h:275:8: error: an attribute list cannot appear here
inline QT_DEPRECATED void qt_mac_set_dock_menu(QMenu *menu) { menu->setAsDockMenu(); }
```

**Comment by eugene-so** [comment]
@seanPhill : Thanks.  This PR was meant to deal with Catalina build issues first.  There are still one or two more PRs after this one (already in queue) that bring in additional changes.  I'm not sure if they address the issue you have brought up, but I think we should merge these changes incrementally.

**Comment by seanPhill** [comment]
> @seanPhill : Thanks. This PR was meant to deal with Catalina build issues first. There are still one or two more PRs after this one (already in queue) that bring in additional changes. I'm not sure if they address the issue you have brought up, but I think we should merge these changes incrementally.

I totally agree. At least the Github Actions builds still run fine on macOS Big Sur (and Catalina).
